### ISSUE TITLE
用法疑问

### ISSUE THREAD

**Issue by hdjhdjhdj** [hashencode/react-native-orientation-locker-cn#1]
页面顶部引入
import Orientation from 'react-native-orientation-locker';

在用户点击同意 隐私政策和用户协议后
调用Orientation.init()
需要强制横屏
调用 Orientation.lockToLandscapeLeft();

是这样的顺序吗？

**Comment by hdjhdjhdj** [comment]
只需要切换横竖屏，AndroidManifest.xml 里面需要加这个权限吗？
android.permission.BODY_SENSORS

**Comment by hashencode** [comment]
不需要初始化也可以直接调用
不需要增加 BODY_SENSORS 权限
具体用法参照 https://github.com/wonday/react-native-orientation-locker 和 https://github.com/zhangyeke/react-native-orientation-locker，这个仓库只是为了创建我自己的npm包，避免初始化问题

**Comment by hdjhdjhdj** [comment]
那个库，上架会提示传感器权限问题。
我想用你这个库，加了init方法

**Comment by hashencode** [comment]
直接安装 react-native-orientation-locker-cn，或者fork一份自己做成npm包
